Repository FloSchuberth/cSEM, pull requests merged in 2018-10, with the labels that each got.

#114 Second order factors in cSEM
  DESCRIPTION
  R/00_csem.R
  R/00_foreman.R
  R/csem_data.R
  R/csem_model.R
  R/estimators_weights.R
  R/helper_csem.R
  R/helper_foreman.R
  R/postestimate_fit.R
  R/postestimate_verify.R
  R/zz_arguments.R
  man/calculate2ndOrder.Rd
  man/calculateCorrectionFactors.Rd
  man/calculateIndicatorCor.Rd
  man/calculateWeightsFixed.Rd
  man/calculateWeightsGSCA.Rd
  man/convertModel.Rd
  man/csem.Rd
  man/csem_arguments.Rd
  man/foreman.Rd
  man/processData.Rd
  man/testMICOM.Rd
  man/verify.Rd
Labels: bug-fix, enhancement

#123 HTMT, rennaming `check()` to `assess()`, restructuring
  NAMESPACE
  R/000_new.R
  R/csem_fit_measures.R
  R/helper_assess.R
  R/helper_summarize.R
  R/postestimate_assess.R
  R/postestimate_fit.R
  R/zz_arguments.R
  R/zz_print.R
  man/HTMT.Rd
  man/RMS.Rd
  man/SRMR.Rd
  man/assess.Rd
  man/calculateCompositeConstructCV.Rd
  man/calculateCorrectionFactors.Rd
  man/calculateLoadings.Rd
  man/calculateOuterWeightsPLS.Rd
  man/csem_arguments.Rd
  man/effects.Rd
Labels: Review existing code, enhancement, package-design

#127 Issue 126
  R/csem_distance_measures.R
  R/helper_assess.R
  R/postestimate_fit.R
  R/postestimate_test_MGD.R
  R/postestimate_test_OMF.R
  R/postestimate_verify.R
  R/zz_arguments.R
Labels: enhancement

#130 Major changes to postestimation functions
  NAMESPACE
  R/00_cca.R
  R/00_csem.R
  R/00_foreman.R
  R/estimators_weights.R
  R/helper_csem.R
  R/helper_estimators_weights.R
  R/helper_foreman.R
  R/postestimate_assess.R
  R/postestimate_fit.R
  R/postestimate_summarize.R
  R/postestimate_test.R
  R/postestimate_verify.R
  R/zz_arguments.R
  R/zz_print.R
  man/assess.Rd
  man/calculateCorrectionFactors.Rd
  man/calculateInnerWeightsPLS.Rd
  man/calculateOuterWeightsPLS.Rd
  man/calculateWeightsFixed.Rd
  man/calculateWeightsGSCA.Rd
  man/calculateWeightsKettenring.Rd
  man/calculateWeightsPLS.Rd
  man/calculateWeightsUnit.Rd
  man/csem.Rd
  man/csem_arguments.Rd
  man/fit.Rd
  man/foreman.Rd
  man/print.cSEMSummarize_2ndorder.Rd
  man/print.cSEMSummarize_default.Rd
  man/print.cSEMVerify_2ndorder.Rd
  man/print.cSEMVerify_default.Rd
  man/summarize.Rd
  man/test.Rd
  man/testMICOM.Rd
  man/verify.Rd
Labels: Review existing code, bug-fix, enhancement, package-design

#131 Changes to `testOMF()` and `testMGD()`
  NAMESPACE
  R/000_new.R
  R/00_csem.R
  R/helper_assess.R
  R/helper_foreman.R
  R/postestimate_test_MGD.R
  R/postestimate_test_MICOM.R
  R/postestimate_test_OMF.R
  R/zz_arguments.R
  R/zz_print.R
  man/SRMR.Rd
  man/csem_arguments.Rd
  man/testMGD.Rd
  man/testMICOM.Rd
  man/testOMF.Rd
Labels: Review existing code, enhancement

#134 Review testMICOM and harmonizing the testXXX family of functions
  NAMESPACE
  R/postestimate_test_MGD.R
  R/postestimate_test_MICOM.R
  R/postestimate_test_OMF.R
  R/zz_arguments.R
  R/zz_print.R
  man/csem_arguments.Rd
  man/testMGD.Rd
  man/testMICOM.Rd
  man/testOMF.Rd
Labels: Review existing code, enhancement, package-design

#137 Implement testMICOM
  NAMESPACE
  R/00_csem.R
  R/csem_distance_measures.R
  R/postestimate_test_MGD.R
  R/postestimate_test_MICOM.R
  R/postestimate_test_OMF.R
  R/zz_print.R
  man/print.cSEMTestMICOM.Rd
  man/testMGD.Rd
  man/testMICOM.Rd
Labels: Review existing code, enhancement
