Repository FloSchuberth/cSEM, pull requests merged in 2018-09, with the labels that each got.

#97 postemiate test v1.0
  DESCRIPTION
  NAMESPACE
  R/000_new.R
  R/00_cca.R
  R/00_csem.R
  R/00_foreman.R
  R/csem_fit_measures.R
  R/estimators_weights.R
  R/postestimate_check.R
  R/postestimate_fit.R
  R/postestimate_summarize.R
  R/postestimate_test.R
  R/postestimate_test_MGD.R
  R/postestimate_test_OMF.R
  R/postestimate_verify.R
  R/zz_.onAttach.R
  R/zz_print.R
  README.md
  README.rmd
  man/cSEM-package.Rd
  man/check.Rd
  man/csem.Rd
  man/effects.cSEMResults.Rd
  man/print.cSEMSummarize.Rd
  man/print.cSEMTestMGD.Rd
  man/summarize.Rd
  man/summary.cSEMResults.Rd
  man/testMGD.Rd
  man/verify.Rd
Labels: enhancement

#98 including the option to use the theil-sen estimator for the correlati…
  DESCRIPTION
  R/00_foreman.R
  R/helper_foreman.R
  R/zz_arguments.R
  man/calculateCorTheilSen.Rd
  man/calculateIndicatorCor.Rd
  man/csem.Rd
  man/csem_arguments.Rd
  man/estimateTheilSen.Rd
  man/foreman.Rd
Labels: enhancement

#102 initial version GSCA
  R/00_csem.R
  R/gsca.R
  R/zz_templates.R
Labels: enhancement

#100 Issue #84
  NAMESPACE
  R/000_new.R
  R/csem_model.R
  man/summary.cSEMResults.Rd
Labels: enhancement

#109 fixes #106
  R/00_foreman.R
  R/estimators_weights.R
  man/calculateWeightsKettenring.Rd
  man/calculateWeightsPLS.Rd
  man/calculateWeightsUnit.Rd
Labels: Review existing code, package-design

#113 fixes #112
  DESCRIPTION
  R/00_foreman.R
  R/csem_data.R
  R/helper_foreman.R
  R/zz_arguments.R
  man/calculateIndicatorCor.Rd
  man/calculateWeightsFixed.Rd
  man/calculateWeightsGSCA.Rd
  man/calculateWeightsKettenring.Rd
  man/calculateWeightsPLS.Rd
  man/calculateWeightsUnit.Rd
  man/csem_arguments.Rd
  man/foreman.Rd
  man/processData.Rd
  man/testMICOM.Rd
Labels: Review existing code

#115 Should fix #110
  R/00_foreman.R
  R/helper_foreman.R
Labels: enhancement
